# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ramsada.io
title: RAMSADA.io
email: ramsadanajar@gmail.com
author: Najar Ramsada
description: > # "Write an awesome description for your new site here. 
  Made by Najar Ramsada.
copyright: 'Copyright &copy; 2018 Najar Ramsada. All Rights Reserved.'
credits: 'Site by <a href="https://au.linkedin.com/in/najarramsada/">Najar Ramsada</a><br/><a href="https://github.com/najarramsada/landing/blob/master/README.md">Credits</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://au.linkedin.com/in/najarramsada
  - title: google
    url: "mailto:ramsadanajar@gmail.com?Subject=ramsada.io"
  - title: github
    url: https://github.com/najarramsada/
