# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ramsada.io
title: RAMSADA.io
email: ramsadanajar@gmail.com
author: Najar Ramsada
description: > # "Write an awesome description for your new site here. 
  Made by Najar Ramsada.
copyright: 'Copyright &copy; 2018 Najar Ramsada. All Rights Reserved.'
credits: 'Credits: Landing Page by <a href="http://startbootstrap.com/">Start Bootstrap</a>, made by Najar Ramsada'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: ""
  - title: github
    url: https://github.com/najarramsada/
  - title: linkedin
    url: https://au.linkedin.com/in/najarramsada
